// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0ukKKIOkdqRYmAD6bkRFCvm70_vjoKa8',
    appId: '1:990430189954:android:5194024cababbcaf37979b',
    messagingSenderId: '990430189954',
    projectId: 'we-chat-dd51d',
    storageBucket: 'we-chat-dd51d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGxhDMRCPJEu__Dsac03ApoZDfCeOhiU4',
    appId: '1:990430189954:ios:b823284abeb83bc637979b',
    messagingSenderId: '990430189954',
    projectId: 'we-chat-dd51d',
    storageBucket: 'we-chat-dd51d.appspot.com',
    androidClientId: '990430189954-nos1qr2d07423rt2m1qj5tvt94qfqbel.apps.googleusercontent.com',
    iosClientId: '990430189954-hhbl4ci2clm6k8otcarg89kh3rui6cis.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat01',
  );
}
